export const GET_RECIPES= "GET_RECIPES";
export const GET_RECIPES_ID="GET_RECIPES_ID";
export const GET_RECIPES_NAME="GET_RECIPES_NAME";
export const GET_CLEAR="GET_CLEAR";
export const GET_CLEAR_HOME="GET_CLEAR_HOME";
export const GET_TYPES="GET_TYPES";
export const GET_ALL_TYPES="GET_ALL_TYPES";
export const GET_ORDER_NAME="GET_ORDER_NAME";
export const GET_ORDER_HSCORE="GET_ORDER_HSCORE";
export const GET_ORDER_CREATE="GET_ORDER_CREATE";

